services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--loglevel", "nothing"]

  rate-limiter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rate-limiter
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
      - REQ_LIMIT=7
      - BLOCK_TIME_IP=10
      - BLOCK_TIME_TOKEN=15
